import React, { useState } from 'react';
import { fetchTransactionBytecode } from '../utils/etherscanApi';
import { Buffer } from 'buffer';
import { createEVM } from '../../evm/src/constructors';

window.Buffer = window.Buffer || Buffer;

const App: React.FC = () => {
  const [transactionId, setTransactionId] = useState('');
  const [status, setStatus] = useState<string | null>(null);
  const [output, setOutput] = useState<string | null>(null);

  const handleSubmit = async () => {
    try {
      setStatus('Fetching bytecode from Etherscan...');
      setOutput(null); // Clear old data

      // 1) Fetch the bytecode
      const bytecode = await fetchTransactionBytecode(transactionId);
      if (!bytecode || bytecode.length < 2) {
        throw new Error('Invalid bytecode received. Check your transaction ID.');
      }

      // 2) Run the EVM
      setStatus('Creating and running the EVM...');
      const evm = await createEVM();
      const res = await evm.runCode({
        code: Uint8Array.from(Buffer.from(bytecode.slice(2), 'hex')),
        gasLimit: BigInt(0xffff),
      });

      if (!res.runState?.synthesizer?.placements) {
        throw new Error('No placements generated by the synthesizer.');
      }

      // Convert placements to a plain object
      const rawMap = res.runState.synthesizer.placements;
      const placementsObj = Object.fromEntries(rawMap.entries());

      // 3) Send placements to the server
      setStatus('Finalizing placements on the server...');
      const response = await fetch('http://localhost:3001/api/finalize', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ placements: placementsObj }),
      });

      if (!response.ok) {
        throw new Error(`Server returned status ${response.status}`);
      }

      const json = await response.json();
      if (!json.ok) {
        throw new Error(json.error || 'Unknown server error.');
      }

      // Combine server result and bytecode into a single object
      const dataToSave = {
        finalizeResult: json.data || {},
        sourceBytecode: bytecode,
      };

      // Update state
      setOutput(JSON.stringify(dataToSave, null, 2));
      setStatus('Process complete!');
    } catch (error) {
      console.error('Error:', error);
      setStatus(`Error: ${error instanceof Error ? error.message : String(error)}`);
      setOutput(null);
    }
  };

  // Download the output JSON
  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob([output], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'finalize-result.json';
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ padding: '20px' }}>
      <h1>Synthesizer Developer Playground</h1>
      <input
        type="text"
        value={transactionId}
        onChange={(e) => setTransactionId(e.target.value)}
        placeholder="Enter Transaction ID"
        style={{
          padding: '10px',
          width: '300px',
          marginRight: '10px',
          border: '1px solid #ccc',
          borderRadius: '4px',
        }}
      />
      <button
        onClick={handleSubmit}
        style={{
          padding: '10px 20px',
          background: '#007bff',
          color: 'white',
          border: 'none',
          borderRadius: '4px',
          cursor: 'pointer',
        }}
      >
        Process
      </button>
      <div style={{ marginTop: '20px' }}>
        {status && <p>{status}</p>}
        {output && (
          <button
            onClick={handleDownload}
            style={{
              padding: '10px 20px',
              background: '#28a745',
              color: 'white',
              border: 'none',
              borderRadius: '4px',
              cursor: 'pointer',
            }}
          >
            Download JSON
          </button>
        )}
      </div>
    </div>
  );
};

export default App;
