// server/index.ts
import 'dotenv/config';
import express, { Request, Response } from 'express';
import cors from 'cors';
import bodyParser from 'body-parser';
import { SynthesizerAdapter } from '@tokamak-zk-evm/synthesizer';

// If your environment supports top-level await (Node 18+ with "type": "module"):
import {
  STORAGE_IN_PLACEMENT_INDEX, 
  RETURN_PLACEMENT_INDEX, 
  STORAGE_OUT_PLACEMENT_INDEX 
} from '@tokamak-zk-evm/synthesizer';

// A Node/server-side version of fetchTransactionBytecode
// (Make sure it uses axios or node-fetch, not window.fetch)
import { fetchTransactionBytecode } from '../utils/etherscanApi.js';

const app = express();
app.use(cors());
app.use(bodyParser.json());

// Example route: POST /api/parseTransaction
app.post('/api/parseTransaction', async (req: Request, res: Response) => {
  try {
    const { txId } = req.body;
    if (!txId) {
      return res.status(400).json({ ok: false, error: 'No transaction ID provided' });
    }

    // 1) Fetch bytecode, "from", "to" from Etherscan (server-side)
    const { bytecode, from, to } = await fetchTransactionBytecode(txId);
    if (!bytecode || !from || !to) {
      throw new Error('Invalid transaction data from Etherscan');
    }

    // 2) Create SynthesizerAdapter & parse the transaction in memory
    const adapter = new SynthesizerAdapter();
    const {
      executionResult,
      permutation,
      placementInstance,
    } = await adapter.parseTransaction({
      contractAddr: to,    // Must be TON, USDT, or USDC
      calldata: bytecode,  // The transaction input (i.e., "input" field)
      sender: from,
    });

    // 3) Extract logs/storage from the synthesizer placements
    if (!executionResult.runState?.synthesizer?.placements) {
      throw new Error('No placements generated by the synthesizer.');
    }
    const placementsMap = executionResult.runState.synthesizer.placements;

    // Storage placements
    const storageLoadPlacement = placementsMap.get(STORAGE_IN_PLACEMENT_INDEX);
    const logsPlacement = placementsMap.get(RETURN_PLACEMENT_INDEX);
    const storageStorePlacement = placementsMap.get(STORAGE_OUT_PLACEMENT_INDEX);

    const storageLoad = storageLoadPlacement?.inPts || [];
    const storageStore = storageStorePlacement?.outPts || [];
    const _logsData = logsPlacement?.outPts || [];

    // Example log parsing logic - modified to handle BigInt serialization
    const logs: Array<{ topics: string[]; valueDec: string; valueHex: string }> = [];
    let prevIdx = -1;
    for (const _logData of _logsData) {
      const idx = _logData.pairedInputWireIndices![0];
      if (idx !== prevIdx) {
        logs.push({ 
          topics: [], 
          valueDec: _logData.value.toString(), // Convert BigInt to string
          valueHex: _logData.valueHex 
        });
      } else {
        logs[idx].topics.push(_logData.valueHex);
      }
      prevIdx = idx;
    }

    // Helper function to convert BigInt values to strings in any object
    const convertBigIntsToStrings = (obj: any) => 
      JSON.parse(JSON.stringify(obj, (_, value) =>
        typeof value === 'bigint' ? value.toString() : value
      ));

    // 4) Send final results back to the client
    res.json({
      ok: true,
      data: {
        from,
        to,
        logs,
        storageLoad: convertBigIntsToStrings(storageLoad),
        storageStore: convertBigIntsToStrings(storageStore),
        permutation: convertBigIntsToStrings(permutation),
        placementInstance: convertBigIntsToStrings(placementInstance),
      },
    });
  } catch (error) {
    console.error('Error in /api/parseTransaction:', error);
    res.status(500).json({ ok: false, error: (error as Error).message });
  }
});

app.listen(3001, () => {
  console.log('Server running on port 3001');
});
