import 'dotenv/config';
import express, { Request, Response } from 'express';
import cors from 'cors';
import bodyParser from 'body-parser';
import { SynthesizerAdapter } from '@tokamak-zk-evm/synthesizer';

// Import constants using a valid file URL for Windows
const {
  STORAGE_IN_PLACEMENT_INDEX,
  RETURN_PLACEMENT_INDEX,
  STORAGE_OUT_PLACEMENT_INDEX,
} = await import('file:///C:/Users/kyros/Documents/tokamak-zk-evm-8/node_modules/@tokamak-zk-evm/synthesizer/src/tokamak/constant/constants.js');

// A Node/server-side version of fetchTransactionBytecode
// (Make sure it uses axios or node-fetch, not window.fetch)
import { fetchTransactionBytecode } from '../utils/etherscanApi.js';

const app = express();
app.use(cors());
app.use(bodyParser.json());

// Example route: POST /api/parseTransaction
app.post('/api/parseTransaction', async (req: Request, res: Response) => {
  try {
    const { txId } = req.body;
    if (!txId) {
      return res.status(400).json({ ok: false, error: 'No transaction ID provided' });
    }

    // 1) Fetch bytecode, "from", "to" from Etherscan (server-side)
    const { bytecode, from, to } = await fetchTransactionBytecode(txId);
    if (!bytecode || !from || !to) {
      throw new Error('Invalid transaction data from Etherscan');
    }

    // 2) Create SynthesizerAdapter & parse the transaction in memory
    const adapter = new SynthesizerAdapter();
    const {
      executionResult,
      permutation,
      placementInstance,
    } = await adapter.parseTransaction({
      contractAddr: to,    // Must be TON, USDT, or USDC
      calldata: bytecode,  // The transaction input (i.e., "input" field)
      sender: from,
    });

    // 3) Extract logs/storage from the synthesizer placements
    if (!executionResult.runState?.synthesizer?.placements) {
      throw new Error('No placements generated by the synthesizer.');
    }
    const placementsMap = executionResult.runState.synthesizer.placements;

    // Storage placements
    const storageLoadPlacement = placementsMap.get(STORAGE_IN_PLACEMENT_INDEX);
    const logsPlacement = placementsMap.get(RETURN_PLACEMENT_INDEX);
    const storageStorePlacement = placementsMap.get(STORAGE_OUT_PLACEMENT_INDEX);

    const storageLoad = storageLoadPlacement?.inPts || [];
    const storageStore = storageStorePlacement?.outPts || [];
    const _logsData = logsPlacement?.outPts || [];

    // Example log parsing logic - modified to safely append topics
    const logs: Array<{ topics: string[]; valueDec: bigint; valueHex: string }> = [];
    let prevIdx = -1;
    for (const _logData of _logsData) {
      const idx = _logData.pairedInputWireIndices?.[0] ?? -1;  // Default to -1 if undefined
      // If the current log index differs from the previous one or logs array is empty, create a new log entry
      if (idx !== prevIdx || logs.length === 0) {
        logs.push({ topics: [], valueDec: _logData.value, valueHex: _logData.valueHex });
      } else {
        // Append to the topics of the most recent log entry
        logs[logs.length - 1].topics.push(_logData.valueHex);
      }
      prevIdx = idx;
    }

    // 4) Send final results back to the client
    res.json({
      ok: true,
      data: {
        from,
        to,
        logs,
        storageLoad,
        storageStore,
        permutation,       // In-memory finalization
        placementInstance, // In-memory finalization
      },
    });
  } catch (error) {
    console.error('Error in /api/parseTransaction:', error);
    res.status(500).json({ ok: false, error: (error as Error).message });
  }
});

app.listen(3001, () => {
  console.log('Server running on port 3001');
});
