services:
  cli: &cli_base
    build:
      context: .
      dockerfile: dockerfile
    image: tokamak-zkevm:dev
    command: bash
    volumes:
      - type: bind
        source: .
        target: /workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
    environment:
      TOKAMAK_ZK_EVM_ROOT: /workspace

  cli-gpu:
    <<: *cli_base
    profiles:
      - gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
