import {
  RuntimeArtifactFileRole,
  createCurveRuntime,
  decodeVerifierBinaryResult,
  parseRuntimeArtifactBundleManifest,
  proveBinary,
  verifyBinary,
  type RuntimeArtifactBundleManifest,
} from "../../src/index.js";

declare global {
  interface Window {
    __tokamakProverResult?: BrowserProverResult;
  }
}

interface BrowserProverResult {
  readonly status: "pending" | "ok" | "error";
  readonly valid?: boolean;
  readonly proofBytes?: number;
  readonly timings?: readonly BrowserTiming[];
  readonly error?: string;
}

interface BrowserTiming {
  readonly label: string;
  readonly ms: number;
}

interface BinaryProverVerifierFixture {
  readonly proverProofWitnessManifest: RuntimeArtifactBundleManifest;
  readonly proverCrsPreparedDataManifest: RuntimeArtifactBundleManifest;
  readonly verifierProofManifest: RuntimeArtifactBundleManifest;
  readonly verifierSetupManifest: RuntimeArtifactBundleManifest;
  readonly resolvePreparedFile: (path: string) => Promise<Uint8Array>;
}

window.__tokamakProverResult = { status: "pending" };

main().catch((error: unknown) => {
  window.__tokamakProverResult = {
    status: "error",
    error: error instanceof Error ? error.stack ?? error.message : String(error),
  };
});

async function main(): Promise<void> {
  const timings: BrowserTiming[] = [];
  const fixture = await timed(timings, "load fixture manifests", loadPreparedBinaryFixture);
  const runtime = await timed(timings, "create curve runtime", () => createCurveRuntime());

  try {
    const proof = await timed(timings, "prove binary", () =>
      proveBinary(
        runtime,
        fixture.proverProofWitnessManifest,
        fixture.proverCrsPreparedDataManifest,
        fixture.resolvePreparedFile,
      ),
    );
    const verificationResult = await timed(timings, "verify generated proof", () =>
      verifyBinary(
        runtime,
        fixture.verifierProofManifest,
        fixture.verifierSetupManifest,
        createGeneratedProofResolver(fixture.verifierProofManifest, fixture.resolvePreparedFile, proof),
        {
          randomScalar: () => runtime.Fr.one,
        },
      ),
    );
    const valid = decodeVerifierBinaryResult(verificationResult);
    if (!valid) {
      throw new Error("Browser verifier rejected the proof generated by browser prover.");
    }

    window.__tokamakProverResult = {
      status: "ok",
      valid,
      proofBytes: proof.byteLength,
      timings,
    };
  } finally {
    await timed(timings, "terminate curve runtime", () => runtime.terminate());
  }
}

async function loadPreparedBinaryFixture(): Promise<BinaryProverVerifierFixture> {
  const proverProofWitnessManifest = parseRuntimeArtifactBundleManifest(
    await fetchJson("/fixtures/small/runtime/prover-proof-witness-input/manifest.json"),
  );
  const proverCrsPreparedDataManifest = parseRuntimeArtifactBundleManifest(
    await fetchJson("/fixtures/small/runtime/prover-crs-prepared-data/manifest.json"),
  );
  const verifierProofManifest = parseRuntimeArtifactBundleManifest(
    await fetchJson("/fixtures/small/runtime/verifier-proof-input/manifest.json"),
  );
  const verifierSetupManifest = parseRuntimeArtifactBundleManifest(
    await fetchJson("/fixtures/small/runtime/verifier-setup-input/manifest.json"),
  );

  return {
    proverProofWitnessManifest,
    proverCrsPreparedDataManifest,
    verifierProofManifest,
    verifierSetupManifest,
    resolvePreparedFile: (artifactPath) => fetchBinary(`/fixtures/small/runtime/${artifactPath}`),
  };
}

function createGeneratedProofResolver(
  verifierProofManifest: RuntimeArtifactBundleManifest,
  resolvePreparedFile: (path: string) => Promise<Uint8Array>,
  generatedProof: Uint8Array,
): (artifactPath: string) => Promise<Uint8Array> {
  const proofPath = requireBundleRolePath(verifierProofManifest, RuntimeArtifactFileRole.Proof);

  return async (artifactPath: string): Promise<Uint8Array> => {
    if (artifactPath === proofPath) {
      return generatedProof;
    }

    return resolvePreparedFile(artifactPath);
  };
}

function requireBundleRolePath(manifest: RuntimeArtifactBundleManifest, role: RuntimeArtifactFileRole): string {
  const matches = manifest.files.filter((file) => file.role === role);
  if (matches.length !== 1) {
    throw new Error(`${manifest.kind} bundle must contain exactly one '${role}' file.`);
  }

  return matches[0].path;
}

async function fetchJson<T>(path: string): Promise<T> {
  const response = await fetch(path);
  if (!response.ok) {
    throw new Error(describePreparedFixtureFetchFailure(path, response.status));
  }

  return (await response.json()) as T;
}

async function fetchBinary(path: string): Promise<Uint8Array> {
  const response = await fetch(path);
  if (!response.ok) {
    throw new Error(describePreparedFixtureFetchFailure(path, response.status));
  }

  return new Uint8Array(await response.arrayBuffer());
}

async function timed<T>(timings: BrowserTiming[], label: string, callback: () => Promise<T>): Promise<T> {
  console.log(`Starting ${label}...`);
  const start = performance.now();
  const result = await callback();
  const ms = performance.now() - start;
  timings.push({ label, ms });
  console.log(`Finished ${label} in ${formatDuration(ms)}.`);

  return result;
}

function formatDuration(milliseconds: number): string {
  if (milliseconds < 1000) {
    return `${milliseconds.toFixed(0)} ms`;
  }

  return `${(milliseconds / 1000).toFixed(2)} s`;
}

function describePreparedFixtureFetchFailure(path: string, status: number): string {
  if (path.startsWith("/fixtures/small/runtime/")) {
    return [
      `Failed to fetch prepared prover runtime fixture file ${path}: ${status}.`,
      "Prepare owner package outputs, run npm run fixtures:copy, then run npm run fixtures:prepare.",
    ].join(" ");
  }

  return `Failed to fetch ${path}: ${status}.`;
}
