import {
  BackendWasmError,
  begin,
  install as installProver,
  prove,
  type ProverInput,
} from "../../src/prover/index.js";
import {
  install as installVerifier,
  verify,
  type VerifierInput,
} from "../../src/verifier/index.js";

declare global {
  interface Window {
    __tokamakProverResult?: BrowserProverResult;
  }
}

interface BrowserProverResult {
  readonly status: "pending" | "ok" | "error";
  readonly mode?: ProverExecutionMode;
  readonly valid?: boolean;
  readonly proofBytes?: number;
  readonly timings?: readonly BrowserTiming[];
  readonly error?: string;
}

type ProverExecutionMode = "one-call" | "staged";

interface BrowserTiming {
  readonly label: string;
  readonly ms: number;
}

interface BinaryProverVerifierFixture {
  readonly prover: ProverInput;
  readonly verifier: VerifierInput;
}

window.__tokamakProverResult = { status: "pending" };

main().catch((error: unknown) => {
  window.__tokamakProverResult = {
    status: "error",
    error: error instanceof Error ? error.stack ?? error.message : String(error),
  };
});

async function main(): Promise<void> {
  const timings: BrowserTiming[] = [];
  const mode = readExecutionMode();
  const fixture = await timed(timings, "load fixture binaries", loadPreparedBinaryFixture);

  await expectBackendError(() => prove(fixture.prover), "INSTALL_REQUIRED");
  await expectBackendError(
    () => installProver({ chunkSizeExponent: 20 }),
    "INVALID_OPTION",
  );

  const [proverInstallation, concurrentInstallation] = await timed(
    timings,
    "install prover",
    () => Promise.all([
      installProver({ chunkSizeExponent: 18 }),
      installProver(),
    ]),
  );
  if (proverInstallation.chunkSize !== 262_144) {
    throw new Error("Prover installation returned an unexpected chunk size.");
  }
  if (concurrentInstallation.chunkSize !== proverInstallation.chunkSize) {
    throw new Error("Concurrent prover install calls returned inconsistent configuration.");
  }

  const proofPromise = mode === "staged"
    ? timed(timings, "prove binary staged", async () => {
        const session = await begin(fixture.prover);
        try {
          await expectBackendError(() => prove(fixture.prover), "BUSY");
          await session.proveArithmetic();
          await session.proveCopy();
          await session.proveBinding();
          return await session.finalize();
        } catch (error) {
          session.dispose();
          throw error;
        }
      })
    : timed(timings, "prove binary one-call", () => prove(fixture.prover));
  if (mode === "one-call") {
    await expectBackendError(() => prove(fixture.prover), "BUSY");
  }
  await expectBackendError(
    () => installProver({ chunkSizeExponent: 17 }),
    "BUSY",
  );
  const sameConfiguration = await installProver({ chunkSizeExponent: 18 });
  if (sameConfiguration.chunkSize !== proverInstallation.chunkSize) {
    throw new Error("Same-value prover install changed the active configuration.");
  }
  const proof = await proofPromise;
  const updatedConfiguration = await installProver({ chunkSizeExponent: 17 });
  const preservedConfiguration = await installProver();
  if (
    updatedConfiguration.chunkSizeExponent !== 17
    || preservedConfiguration.chunkSizeExponent !== 17
  ) {
    throw new Error("Optionless prover install did not preserve the updated configuration.");
  }
  if (mode === "staged") {
    await timed(timings, "check staged session lifecycle", () =>
      checkStagedSessionLifecycle(fixture.prover)
    );
  }

  await timed(timings, "install verifier", installVerifier);
  const verificationResult = await timed(timings, "verify generated proof", () =>
    verify({ ...fixture.verifier, proof })
  );
  if (!verificationResult) {
    throw new Error("Browser verifier rejected the proof generated by browser prover.");
  }

  window.__tokamakProverResult = {
    status: "ok",
    mode,
    valid: verificationResult,
    proofBytes: proof.byteLength,
    timings,
  };
}

async function checkStagedSessionLifecycle(input: ProverInput): Promise<void> {
  const disposedSession = await begin(input);
  disposedSession.dispose();
  await expectBackendError(() => disposedSession.proveArithmetic(), "RUNTIME_FAILED");

  const invalidSequenceSession = await begin(input);
  await expectBackendError(() => invalidSequenceSession.proveCopy(), "RUNTIME_FAILED");
  await installProver();
}

function readExecutionMode(): ProverExecutionMode {
  const mode = new URL(window.location.href).searchParams.get("mode");
  if (mode === null || mode === "one-call") {
    return "one-call";
  }
  if (mode === "staged") {
    return mode;
  }
  throw new Error(`Unsupported prover execution mode: ${mode}.`);
}

async function loadPreparedBinaryFixture(): Promise<BinaryProverVerifierFixture> {
  const [witness, permutation, instance, proverCrs, proof, verifierPreprocess] = await Promise.all([
    fetchBinary("/fixtures/small/runtime/witness.bin"),
    fetchBinary("/fixtures/small/runtime/permutation.bin"),
    fetchBinary("/fixtures/small/runtime/instance.bin"),
    fetchBinary("/fixtures/small/runtime/prover-crs.bin"),
    fetchBinary("/fixtures/small/runtime/proof.bin"),
    fetchBinary("/fixtures/small/runtime/verifier-preprocess.bin"),
  ]);

  return {
    prover: { witness, permutation, instance, proverCrs },
    verifier: { proof, instance, verifierPreprocess },
  };
}

async function fetchBinary(path: string): Promise<Uint8Array> {
  const response = await fetch(path);
  if (!response.ok) {
    throw new Error(describePreparedFixtureFetchFailure(path, response.status));
  }

  return new Uint8Array(await response.arrayBuffer());
}

async function timed<T>(timings: BrowserTiming[], label: string, callback: () => Promise<T>): Promise<T> {
  console.log(`Starting ${label}...`);
  const start = performance.now();
  const result = await callback();
  const ms = performance.now() - start;
  timings.push({ label, ms });
  console.log(`Finished ${label} in ${formatDuration(ms)}.`);

  return result;
}

async function expectBackendError(
  operation: () => Promise<unknown>,
  expectedCode: BackendWasmError["code"],
): Promise<void> {
  try {
    await operation();
  } catch (error) {
    if (error instanceof BackendWasmError && error.code === expectedCode) {
      return;
    }
    throw error;
  }
  throw new Error(`Expected BackendWasmError code ${expectedCode}.`);
}

function formatDuration(milliseconds: number): string {
  if (milliseconds < 1000) {
    return `${milliseconds.toFixed(0)} ms`;
  }

  return `${(milliseconds / 1000).toFixed(2)} s`;
}

function describePreparedFixtureFetchFailure(path: string, status: number): string {
  if (path.startsWith("/fixtures/small/runtime/")) {
    return [
      `Failed to fetch prepared prover runtime fixture file ${path}: ${status}.`,
      "Prepare owner package outputs, run npm run fixtures:copy, then run npm run fixtures:prepare.",
    ].join(" ");
  }

  return `Failed to fetch ${path}: ${status}.`;
}
