import {
  createCurveRuntime,
  proveBinary,
  verifyBinary,
  type ProverBinaryInput,
  type VerifierBinaryInput,
} from "../../src/index.js";

declare global {
  interface Window {
    __tokamakProverResult?: BrowserProverResult;
  }
}

interface BrowserProverResult {
  readonly status: "pending" | "ok" | "error";
  readonly valid?: boolean;
  readonly proofBytes?: number;
  readonly timings?: readonly BrowserTiming[];
  readonly error?: string;
}

interface BrowserTiming {
  readonly label: string;
  readonly ms: number;
}

interface BinaryProverVerifierFixture {
  readonly prover: ProverBinaryInput;
  readonly verifier: VerifierBinaryInput;
}

window.__tokamakProverResult = { status: "pending" };

main().catch((error: unknown) => {
  window.__tokamakProverResult = {
    status: "error",
    error: error instanceof Error ? error.stack ?? error.message : String(error),
  };
});

async function main(): Promise<void> {
  const timings: BrowserTiming[] = [];
  const fixture = await timed(timings, "load fixture binaries", loadPreparedBinaryFixture);
  const runtime = await timed(timings, "create curve runtime", () => createCurveRuntime());

  try {
    const proof = await timed(timings, "prove binary", () =>
      proveBinary(runtime, fixture.prover),
    );
    const verificationResult = await timed(timings, "verify generated proof", () =>
      verifyBinary(
        runtime,
        { ...fixture.verifier, proof },
        {
          randomScalar: () => runtime.Fr.one,
        },
      ),
    );
    if (!verificationResult) {
      throw new Error("Browser verifier rejected the proof generated by browser prover.");
    }

    window.__tokamakProverResult = {
      status: "ok",
      valid: verificationResult,
      proofBytes: proof.byteLength,
      timings,
    };
  } finally {
    await timed(timings, "terminate curve runtime", () => runtime.terminate());
  }
}

async function loadPreparedBinaryFixture(): Promise<BinaryProverVerifierFixture> {
  const [witness, permutation, instance, proverCrs, proof, verifierPreprocess] = await Promise.all([
    fetchBinary("/fixtures/small/runtime/witness.bin"),
    fetchBinary("/fixtures/small/runtime/permutation.bin"),
    fetchBinary("/fixtures/small/runtime/instance.bin"),
    fetchBinary("/fixtures/small/runtime/prover-crs.bin"),
    fetchBinary("/fixtures/small/runtime/proof.bin"),
    fetchBinary("/fixtures/small/runtime/verifier-preprocess.bin"),
  ]);

  return {
    prover: { witness, permutation, instance, proverCrs },
    verifier: { proof, instance, verifierPreprocess },
  };
}

async function fetchBinary(path: string): Promise<Uint8Array> {
  const response = await fetch(path);
  if (!response.ok) {
    throw new Error(describePreparedFixtureFetchFailure(path, response.status));
  }

  return new Uint8Array(await response.arrayBuffer());
}

async function timed<T>(timings: BrowserTiming[], label: string, callback: () => Promise<T>): Promise<T> {
  console.log(`Starting ${label}...`);
  const start = performance.now();
  const result = await callback();
  const ms = performance.now() - start;
  timings.push({ label, ms });
  console.log(`Finished ${label} in ${formatDuration(ms)}.`);

  return result;
}

function formatDuration(milliseconds: number): string {
  if (milliseconds < 1000) {
    return `${milliseconds.toFixed(0)} ms`;
  }

  return `${(milliseconds / 1000).toFixed(2)} s`;
}

function describePreparedFixtureFetchFailure(path: string, status: number): string {
  if (path.startsWith("/fixtures/small/runtime/")) {
    return [
      `Failed to fetch prepared prover runtime fixture file ${path}: ${status}.`,
      "Prepare owner package outputs, run npm run fixtures:copy, then run npm run fixtures:prepare.",
    ].join(" ");
  }

  return `Failed to fetch ${path}: ${status}.`;
}
