import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";

import { createCurveRuntime, type AffinePointJson, type CurveRuntime } from "../src/index.js";
import type { VerifierInput } from "../src/verifier/verify-snark.js";

const backendWasmRoot = path.resolve(import.meta.dirname, "..");
const generatedPath = path.join(backendWasmRoot, "src", "verifier", "generated", "sigma-verify.generated.ts");
const checkMode = process.argv.includes("--check");
const inputPath = resolveInputPath(process.argv);

interface SigmaVerifyJson {
  readonly G: AffinePointJson;
  readonly H: AffinePointJson;
  readonly sigma_1: {
    readonly x: AffinePointJson;
    readonly y: AffinePointJson;
  };
  readonly sigma_2: {
    readonly alpha: AffinePointJson;
    readonly alpha2: AffinePointJson;
    readonly alpha3: AffinePointJson;
    readonly alpha4: AffinePointJson;
    readonly gamma: AffinePointJson;
    readonly delta: AffinePointJson;
    readonly eta: AffinePointJson;
    readonly x: AffinePointJson;
    readonly y: AffinePointJson;
  };
  readonly lagrange_KL: AffinePointJson;
}

async function main(): Promise<void> {
  await assertInputFile(inputPath);
  const raw = JSON.parse(await readFile(inputPath, "utf8")) as unknown;
  const sigma = parseSigmaVerifyJson(raw);
  const runtime = await createCurveRuntime();

  try {
    const content = renderGeneratedModule(toVerifierSigma(runtime, sigma));

    if (checkMode) {
      const current = await readFile(generatedPath, "utf8");
      if (current !== content) {
        throw new Error("Generated verifier CRS data is stale. Run npm run verifier-crs:generate.");
      }
      return;
    }

    await mkdir(path.dirname(generatedPath), { recursive: true });
    await writeFile(generatedPath, content, "utf8");
  } finally {
    await runtime.terminate();
  }
}

function resolveInputPath(argv: readonly string[]): string {
  const inputIndex = argv.indexOf("--input");
  if (inputIndex === -1) {
    throw new Error("Verifier CRS generation requires --input <path-to-sigma_verify.json>.");
  }

  const value = argv[inputIndex + 1];
  if (value === undefined || value.trim() === "" || value.startsWith("--")) {
    throw new Error("--input requires a non-empty path to sigma_verify.json.");
  }

  return path.resolve(value);
}

async function assertInputFile(filePath: string): Promise<void> {
  try {
    const inputStat = await stat(filePath);
    if (!inputStat.isFile()) {
      throw new Error("not a file");
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Verifier CRS source artifact is not available at ${filePath}: ${message}`);
  }
}

function toVerifierSigma(runtime: CurveRuntime, sigma: SigmaVerifyJson): VerifierInput["sigma"] {
  return {
    G: runtime.G1.parseAffine(sigma.G),
    H: runtime.G2.parseAffine(sigma.H),
    sigma1: {
      x: runtime.G1.parseAffine(sigma.sigma_1.x),
      y: runtime.G1.parseAffine(sigma.sigma_1.y),
    },
    sigma2: {
      alpha: runtime.G2.parseAffine(sigma.sigma_2.alpha),
      alpha2: runtime.G2.parseAffine(sigma.sigma_2.alpha2),
      alpha3: runtime.G2.parseAffine(sigma.sigma_2.alpha3),
      alpha4: runtime.G2.parseAffine(sigma.sigma_2.alpha4),
      gamma: runtime.G2.parseAffine(sigma.sigma_2.gamma),
      delta: runtime.G2.parseAffine(sigma.sigma_2.delta),
      eta: runtime.G2.parseAffine(sigma.sigma_2.eta),
      x: runtime.G2.parseAffine(sigma.sigma_2.x),
      y: runtime.G2.parseAffine(sigma.sigma_2.y),
    },
    lagrangeKL: runtime.G1.parseAffine(sigma.lagrange_KL),
  };
}

function renderGeneratedModule(sigma: VerifierInput["sigma"]): string {
  return `// Generated by scripts/generate-verifier-crs.ts. Do not edit by hand.
import type { VerifierInput } from "../verify-snark.js";

export const GENERATED_VERIFIER_SIGMA = {
  G: ${renderBytes(sigma.G)},
  H: ${renderBytes(sigma.H)},
  sigma1: {
    x: ${renderBytes(sigma.sigma1.x)},
    y: ${renderBytes(sigma.sigma1.y)},
  },
  sigma2: {
    alpha: ${renderBytes(sigma.sigma2.alpha)},
    alpha2: ${renderBytes(sigma.sigma2.alpha2)},
    alpha3: ${renderBytes(sigma.sigma2.alpha3)},
    alpha4: ${renderBytes(sigma.sigma2.alpha4)},
    gamma: ${renderBytes(sigma.sigma2.gamma)},
    delta: ${renderBytes(sigma.sigma2.delta)},
    eta: ${renderBytes(sigma.sigma2.eta)},
    x: ${renderBytes(sigma.sigma2.x)},
    y: ${renderBytes(sigma.sigma2.y)},
  },
  lagrangeKL: ${renderBytes(sigma.lagrangeKL)},
} as const satisfies VerifierInput["sigma"];
`;
}

function renderBytes(bytes: Uint8Array): string {
  return `Uint8Array.from([${[...bytes].join(",")}])`;
}

function parseSigmaVerifyJson(raw: unknown): SigmaVerifyJson {
  const value = requireRecord(raw, "sigma_verify");
  const sigma1 = requireRecord(value.sigma_1, "sigma_1");
  const sigma2 = requireRecord(value.sigma_2, "sigma_2");

  return {
    G: parseAffinePointJson(value.G, "G"),
    H: parseAffinePointJson(value.H, "H"),
    sigma_1: {
      x: parseAffinePointJson(sigma1.x, "sigma_1.x"),
      y: parseAffinePointJson(sigma1.y, "sigma_1.y"),
    },
    sigma_2: {
      alpha: parseAffinePointJson(sigma2.alpha, "sigma_2.alpha"),
      alpha2: parseAffinePointJson(sigma2.alpha2, "sigma_2.alpha2"),
      alpha3: parseAffinePointJson(sigma2.alpha3, "sigma_2.alpha3"),
      alpha4: parseAffinePointJson(sigma2.alpha4, "sigma_2.alpha4"),
      gamma: parseAffinePointJson(sigma2.gamma, "sigma_2.gamma"),
      delta: parseAffinePointJson(sigma2.delta, "sigma_2.delta"),
      eta: parseAffinePointJson(sigma2.eta, "sigma_2.eta"),
      x: parseAffinePointJson(sigma2.x, "sigma_2.x"),
      y: parseAffinePointJson(sigma2.y, "sigma_2.y"),
    },
    lagrange_KL: parseAffinePointJson(value.lagrange_KL, "lagrange_KL"),
  };
}

function parseAffinePointJson(raw: unknown, label: string): AffinePointJson {
  const value = requireRecord(raw, label);
  if (typeof value.x !== "string" || typeof value.y !== "string") {
    throw new Error(`${label} must contain x and y hex strings.`);
  }

  return {
    x: value.x,
    y: value.y,
  };
}

function requireRecord(value: unknown, label: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error(`${label} must be an object.`);
  }

  return value as Record<string, unknown>;
}

await main();
