import {
  BackendWasmError,
  install as installProver,
  prove,
  type ProverInput,
} from "../../src/prover/index.js";
import {
  install as installPreprocess,
  preprocess,
  type PreprocessInput,
} from "../../src/preprocess/index.js";
import {
  install as installVerifier,
  verify,
  type VerifierInput,
} from "../../src/verifier/index.js";

declare global {
  interface Window {
    __tokamakProverResult?: BrowserProverResult;
  }
}

interface BrowserProverResult {
  readonly status: "pending" | "ok" | "error";
  readonly valid?: boolean;
  readonly proofBytes?: number;
  readonly timings?: readonly BrowserTiming[];
  readonly error?: string;
}

interface BrowserTiming {
  readonly label: string;
  readonly ms: number;
}

interface BinaryWorkflowFixture {
  readonly prover: ProverInput;
  readonly preprocess: PreprocessInput;
  readonly verifier: Omit<VerifierInput, "proof" | "verifierPreprocess">;
}

window.__tokamakProverResult = { status: "pending" };

main().catch((error: unknown) => {
  window.__tokamakProverResult = {
    status: "error",
    error: formatError(error),
  };
});

function formatError(error: unknown): string {
  if (!(error instanceof Error)) return String(error);
  const summary = error.stack ?? error.message;
  const cause = (error as Error & { readonly cause?: unknown }).cause;
  return cause === undefined ? summary : `${summary}\nCaused by: ${formatError(cause)}`;
}

async function main(): Promise<void> {
  const timings: BrowserTiming[] = [];
  const fixture = await timed(timings, "load fixture binaries", loadPreparedBinaryFixture);

  await expectBackendError(() => prove(fixture.prover), "INSTALL_REQUIRED");
  await expectBackendError(() => installProver({ chunkSizeExponent: 20 }), "INVALID_OPTION");

  const [preprocessInstallation, proverInstallation, verifierInstallation] = await timed(
    timings,
    "install runtimes",
    () => Promise.all([
      installPreprocess({ chunkSizeExponent: 17 }),
      installProver({ chunkSizeExponent: 18 }),
      installVerifier(),
    ]),
  );
  if (preprocessInstallation.chunkSize !== 131_072 || proverInstallation.chunkSize !== 262_144) {
    throw new Error("Runtime installation returned an unexpected chunk size.");
  }
  if (verifierInstallation.nativeBackendVersion !== proverInstallation.nativeBackendVersion) {
    throw new Error("Installed runtimes report different native backend versions.");
  }

  const verifierPreprocess = await timed(timings, "preprocess", () => preprocess(fixture.preprocess));
  const proofPromise = timed(timings, "prove", () => prove(fixture.prover));
  await expectBackendError(() => prove(fixture.prover), "BUSY");
  await expectBackendError(() => installProver({ chunkSizeExponent: 17 }), "BUSY");
  const proof = await proofPromise;
  const valid = await timed(timings, "verify", () => verify({
    ...fixture.verifier,
    proof,
    verifierPreprocess,
  }));
  if (!valid) throw new Error("Browser verifier rejected the proof generated by the browser prover.");

  window.__tokamakProverResult = {
    status: "ok",
    valid,
    proofBytes: proof.byteLength,
    timings,
  };
}
async function loadPreparedBinaryFixture(): Promise<BinaryWorkflowFixture> {
  const [witness, selector, permutation, instance, crsManifest] = await Promise.all([
    fetchBinary("/fixtures/small/runtime/witness.bin"),
    fetchBinary("/fixtures/small/runtime/selector.bin"),
    fetchBinary("/fixtures/small/runtime/permutation.bin"),
    fetchBinary("/fixtures/small/runtime/instance.bin"),
    fetchJson("/fixtures/small/runtime/crs/univariate-crs-manifest.json"),
  ]);
  const crs = {
    manifest: crsManifest,
    loadChunk: (relativePath: string) => fetchBinary(`/fixtures/small/runtime/crs/${relativePath}`),
  };
  return {
    prover: { witness, selector, permutation, instance, proverCrs: crs },
    preprocess: { selector, permutation, instance, preprocessCrs: crs },
    verifier: { instance },
  };
}

async function fetchJson(path: string): Promise<unknown> {
  const response = await fetch(path);
  if (!response.ok) throw new Error(`Failed to fetch prepared runtime fixture ${path}: ${response.status}.`);
  return response.json() as Promise<unknown>;
}

async function fetchBinary(path: string): Promise<Uint8Array> {
  const response = await fetch(path);
  if (!response.ok) {
    throw new Error([
      `Failed to fetch prepared runtime fixture ${path}: ${response.status}.`,
      "Run npm run fixtures:copy and npm run fixtures:prepare first.",
    ].join(" "));
  }
  return new Uint8Array(await response.arrayBuffer());
}

async function timed<T>(timings: BrowserTiming[], label: string, operation: () => Promise<T>): Promise<T> {
  const started = performance.now();
  const result = await operation();
  timings.push({ label, ms: performance.now() - started });
  return result;
}

async function expectBackendError(
  operation: () => Promise<unknown>,
  expectedCode: BackendWasmError["code"],
): Promise<void> {
  try {
    await operation();
  } catch (error) {
    if (error instanceof BackendWasmError && error.code === expectedCode) return;
    throw error;
  }
  throw new Error(`Expected BackendWasmError code ${expectedCode}.`);
}
